repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.12
  hooks:
    - id: ruff
      types_or: [ python, pyi ]
      args: [ "--fix", "--exclude=\\.ci,reference,experiments,*__test.py,*__it.py" ]
    - id: ruff-format
      types_or: [ python, pyi ]
      args: [ "--exclude=reference,experiments" ]

- repo: local
  hooks:
    - id: check-marks
      name: Check IT marks
      entry: python .ci/scripts/check_integration_marks.py
      language: system
      types: [python]
      always_run: true
      pass_filenames: false

exclude: |
  ^\.ci.*
  ^reference.*
  ^experiments.*
  ^.*__test.py
  ^.*__it.py
