services:
  pm25ml:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ${HOME}/.config/gcloud/application_default_credentials.json:/app/.config/google-creds.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.config/google-creds.json
    command: ["python", "-m", "pm25ml.run._run_local"]

  pm25ml-imputation:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ${HOME}/.config/gcloud/application_default_credentials.json:/app/.config/google-creds.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.config/google-creds.json
    command: ["python", "-m", "pm25ml.run.impute"]
