[tool.poetry]
name = "india-map"
version = "0.1.0"
description = "Create daily PM2.5 rasters for India."
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.3"
earthengine-api = "^1.5.7"
scikit-learn = "^1.6.1"
xgboost = "^3.0.0"
geopandas = "^1.0.1"
metpy = "^1.6.3"
pyarrow = "^19.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
