main:
  steps:
    - run_pm25ml:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: namespaces/vital-form-455413-p8/jobs/pm25ml
          location: europe-west1
        result: run_job_result

    - start_feature_generation:
        call: googleapis.batch.v1.projects.locations.jobs.create
        args:
          parent: projects/vital-form-455413-p8/locations/europe-west1
          jobId: ${"pm25ml-feature-" + string(int(sys.now()))}
          body:
            allocationPolicy:
              serviceAccount:
                email: pm25ml@vital-form-455413-p8.iam.gserviceaccount.com
              instances:
                - policy:
                    machineType: n4-standard-8     # 8 vCPU / 32 GiB
                    provisioningModel: SPOT        # pre-emptible
            taskGroups:
              - taskCount: 1
                taskSpec:
                  runnables:
                    - container:
                        imageUri: europe-west1-docker.pkg.dev/vital-form-455413-p8/pm25ml/pm25ml:latest
                        commands:
                          - python
                          - -m
                          - pm25ml.feature_generation.generate
                      environment:
                        variables:
                          GCP_PROJECT: vital-form-455413-p8
                          INDIA_SHAPEFILE_ASSET: projects/vital-form-455413-p8
                          CSV_BUCKET_NAME: crea-ee-csv-buffer
                          INGEST_ARCHIVE_BUCKET_NAME: crea-pm25ml-ingest-archive
                          COMBINED_BUCKET_NAME: crea-pm25ml-combined
                          SPATIAL_COMPUTATION_VALUE_COLUMN_REGEX: "^era5_land__.*$"
                          TQDM_DISABLE: "1"
                          START_MONTH: "2018-08-01"
                          END_MONTH: "2025-03-01"
                  computeResource:
                    memoryMib: 32768               # 32 GiB
                    cpuMilli: 8000                 # 8 vCPU
            logsPolicy:
              destination: CLOUD_LOGGING
        result: batch_job_result

    - run_aod_sampling:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: namespaces/vital-form-455413-p8/jobs/pm25ml
          location: europe-west1
          body:
            overrides:
              containerOverrides:
                - args:
                    - python
                    - -m
                    - pm25ml.sample.aod
        result: run_job_result
