name: Load Poetry and Dependencies from Cache
description: Reuses poetry and dependency cache steps
runs:
  using: "composite"
  steps:
    - name: Load poetry install
      uses: actions/cache/restore@v3
      with:
        path: ~/.local
        key: poetry-${{ env.POETRY_VERSION }}-${{ env.PYTHON_VERSION }}

    - name: Load dependencies
      id: cache-deps
      uses: actions/cache/restore@v3
      with:
        path: .venv
        key: pydeps-${{ env.PYTHON_VERSION }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}
