name: Workflow

on:
  push:
    branches: [main]
  pull_request:

env:
  POETRY_VERSION: 2.1.3
  PROJECT_SUBDIR: pm25ml

permissions:
  id-token: write
  contents: read

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache poetry install
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ env.POETRY_VERSION }}

      - uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        env:
          # Used to invalidate the cache when the dependency installation command
          # changes.
          VERSION: v2
        with:
          path: .venv
          key: pydeps-${{ env.VERSION }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-interaction --no-root --only main,dev
        if: steps.cache-deps.outputs.cache-hit != 'true'

  install-package:
    runs-on: ubuntu-latest
    needs: [deps]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/poetry-cache-restore
      - name: Install package
        run: poetry install --no-interaction

  test:
    runs-on: ubuntu-latest
    needs: [deps]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/poetry-cache-restore
      - name: Run tests
        run: poetry run pytest -m "not integration"
  
  integration-test:
    runs-on: ubuntu-latest
    needs: [deps]
    env:
      IT_GEE_ASSET_ROOT: projects/vital-form-455413-p8/assets/integration_tests
      IT_GEE_ASSET_BUCKET_NAME: pm25ml-gee-integration-tests
      GCP_PROJECT: vital-form-455413-p8
      GOOGLE_SERVICE_ACCOUNT_NAME: crea-india-map-github-actions@vital-form-455413-p8.iam.gserviceaccount.com

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/poetry-cache-restore
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: vital-form-455413-p8
          service_account: ${{ env.GOOGLE_SERVICE_ACCOUNT_NAME }}
          workload_identity_provider: 'projects/716476042137/locations/global/workloadIdentityPools/github-wif-pool/providers/crea-org-actions-provider'
          export_environment_variables: true
      - name: Run integration tests
        run: poetry run pytest -m "integration"
  
  mypy:
    runs-on: ubuntu-latest
    needs: [deps]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/poetry-cache-restore
      - name: Run mypy
        run: poetry run mypy ${{ env.PROJECT_SUBDIR }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
