name: Workflow

on:
  push:
    branches: [main]
  pull_request:

env:
  POETRY_VERSION: 2.1.3

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache poetry install
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ env.POETRY_VERSION }}

      - uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}
          
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'

  install-package:
    runs-on: ubuntu-latest
    needs: [deps]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/poetry-cache-restore
      - name: Install package
        run: poetry install --no-interaction

  test:
    runs-on: ubuntu-latest
    needs: [deps]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/poetry-cache-restore
      - name: Run tests
        run: poetry run pytest
  
  mypy:
    runs-on: ubuntu-latest
    needs: [deps]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/poetry-cache-restore
      - name: Run mypy
        run: poetry run mypy pm25ml

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
